# Generated by Django 3.0.8 on 2020-07-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CE', 'CE')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFormModel',
            fields=[
                ('account', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='', max_length=7)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUpdateMarksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_1', models.IntegerField()),
                ('subject_2', models.IntegerField()),
                ('subject_3', models.IntegerField()),
                ('subject_4', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.StudentFormModel')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty')], default='', max_length=7)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Department')),
            ],
        ),
    ]
